// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHp6ZPcntLh6FJsy_aF1s0V8Puahii1xk',
    appId: '1:259704955253:web:b550c283334aafb6cb333c',
    messagingSenderId: '259704955253',
    projectId: 'digi-clinic-e14fa',
    authDomain: 'digi-clinic-e14fa.firebaseapp.com',
    storageBucket: 'digi-clinic-e14fa.appspot.com',
    measurementId: 'G-LB70JQKN17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO9SXW3vlcsBUQayodeMTdZWB3UMzsYHA',
    appId: '1:259704955253:android:2c7641d40683cad1cb333c',
    messagingSenderId: '259704955253',
    projectId: 'digi-clinic-e14fa',
    storageBucket: 'digi-clinic-e14fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkNIDYlozm52-Y3hRxlUqt-9Uu92vHnU',
    appId: '1:259704955253:ios:774660687b5b942dcb333c',
    messagingSenderId: '259704955253',
    projectId: 'digi-clinic-e14fa',
    storageBucket: 'digi-clinic-e14fa.appspot.com',
    iosBundleId: 'com.example.digitalClinicFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQkNIDYlozm52-Y3hRxlUqt-9Uu92vHnU',
    appId: '1:259704955253:ios:774660687b5b942dcb333c',
    messagingSenderId: '259704955253',
    projectId: 'digi-clinic-e14fa',
    storageBucket: 'digi-clinic-e14fa.appspot.com',
    iosBundleId: 'com.example.digitalClinicFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHp6ZPcntLh6FJsy_aF1s0V8Puahii1xk',
    appId: '1:259704955253:web:e9a4ee26991c7fc4cb333c',
    messagingSenderId: '259704955253',
    projectId: 'digi-clinic-e14fa',
    authDomain: 'digi-clinic-e14fa.firebaseapp.com',
    storageBucket: 'digi-clinic-e14fa.appspot.com',
    measurementId: 'G-1VDZ81CCF2',
  );
}
